DROP TABLE IF EXISTS user;
CREATE TABLE user (
     uid INT(10) NOT NULL AUTO_INCREMENT,
     user_name VARCHAR(255) NOT NULL,
     password VARCHAR(255) NOT NULL,
     create_time DATETIME DEFAULT NULL,
     login_time DATETIME DEFAULT NULL,
     logout_time DATETIME DEFAULT NULL,
     PRIMARY KEY(uid)
)ENGINE=InnoDB AUTO_INCREMENT=31798340 DEFAULT CHARSET=utf8;