// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//协议号
type GameMessage int32

const (
	GameMessage__              GameMessage = 0
	GameMessage_Req_EnterTable GameMessage = 1
)

var GameMessage_name = map[int32]string{
	0: "_",
	1: "Req_EnterTable",
}

var GameMessage_value = map[string]int32{
	"_":              0,
	"Req_EnterTable": 1,
}

func (x GameMessage) String() string {
	return proto.EnumName(GameMessage_name, int32(x))
}

func (GameMessage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

//桌子类型
type TableType int32

const (
	TableType_SixPlayer  TableType = 0
	TableType_NinePlayer TableType = 1
)

var TableType_name = map[int32]string{
	0: "SixPlayer",
	1: "NinePlayer",
}

var TableType_value = map[string]int32{
	"SixPlayer":  0,
	"NinePlayer": 1,
}

func (x TableType) String() string {
	return proto.EnumName(TableType_name, int32(x))
}

func (TableType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

//桌子盲注级别
type TableLevel int32

const (
	TableLevel___            TableLevel = 0
	TableLevel_LevelLow_1    TableLevel = 1
	TableLevel_LevelLow_2    TableLevel = 2
	TableLevel_LevelLow_3    TableLevel = 3
	TableLevel_LevelLow_4    TableLevel = 4
	TableLevel_LevelMiddle_1 TableLevel = 5
	TableLevel_LevelMiddle_2 TableLevel = 6
	TableLevel_LevelMiddle_3 TableLevel = 7
	TableLevel_LevelMiddle_4 TableLevel = 8
)

var TableLevel_name = map[int32]string{
	0: "__",
	1: "LevelLow_1",
	2: "LevelLow_2",
	3: "LevelLow_3",
	4: "LevelLow_4",
	5: "LevelMiddle_1",
	6: "LevelMiddle_2",
	7: "LevelMiddle_3",
	8: "LevelMiddle_4",
}

var TableLevel_value = map[string]int32{
	"__":            0,
	"LevelLow_1":    1,
	"LevelLow_2":    2,
	"LevelLow_3":    3,
	"LevelLow_4":    4,
	"LevelMiddle_1": 5,
	"LevelMiddle_2": 6,
	"LevelMiddle_3": 7,
	"LevelMiddle_4": 8,
}

func (x TableLevel) String() string {
	return proto.EnumName(TableLevel_name, int32(x))
}

func (TableLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

//请求入桌
type ReqEnterTable struct {
	Uid                  int64      `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type                 TableType  `protobuf:"varint,2,opt,name=type,proto3,enum=pb.TableType" json:"type,omitempty"`
	Level                TableLevel `protobuf:"varint,3,opt,name=level,proto3,enum=pb.TableLevel" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReqEnterTable) Reset()         { *m = ReqEnterTable{} }
func (m *ReqEnterTable) String() string { return proto.CompactTextString(m) }
func (*ReqEnterTable) ProtoMessage()    {}
func (*ReqEnterTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *ReqEnterTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEnterTable.Unmarshal(m, b)
}
func (m *ReqEnterTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEnterTable.Marshal(b, m, deterministic)
}
func (m *ReqEnterTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEnterTable.Merge(m, src)
}
func (m *ReqEnterTable) XXX_Size() int {
	return xxx_messageInfo_ReqEnterTable.Size(m)
}
func (m *ReqEnterTable) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEnterTable.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEnterTable proto.InternalMessageInfo

func (m *ReqEnterTable) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ReqEnterTable) GetType() TableType {
	if m != nil {
		return m.Type
	}
	return TableType_SixPlayer
}

func (m *ReqEnterTable) GetLevel() TableLevel {
	if m != nil {
		return m.Level
	}
	return TableLevel___
}

func init() {
	proto.RegisterEnum("pb.GameMessage", GameMessage_name, GameMessage_value)
	proto.RegisterEnum("pb.TableType", TableType_name, TableType_value)
	proto.RegisterEnum("pb.TableLevel", TableLevel_name, TableLevel_value)
	proto.RegisterType((*ReqEnterTable)(nil), "pb.ReqEnterTable")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x6a, 0x83, 0x40,
	0x10, 0x80, 0xb3, 0x6b, 0xb4, 0x75, 0x8a, 0x32, 0x9d, 0x93, 0xc7, 0xb4, 0xf4, 0x20, 0x1e, 0x84,
	0x68, 0x9e, 0xa0, 0x50, 0x7a, 0x49, 0x4a, 0xb0, 0xb9, 0x2f, 0x8a, 0x43, 0xb0, 0x98, 0x68, 0xd4,
	0xfe, 0xf8, 0x36, 0x3d, 0xf7, 0x29, 0x4b, 0x36, 0x21, 0x41, 0x6f, 0xfb, 0x7d, 0xf3, 0xc1, 0x2c,
	0x03, 0xf6, 0xae, 0xdd, 0x86, 0x75, 0x53, 0x75, 0x15, 0xc9, 0x3a, 0x7b, 0xfc, 0x00, 0x27, 0xe1,
	0xc3, 0xcb, 0xbe, 0xe3, 0x66, 0x93, 0x66, 0x25, 0x13, 0x82, 0xf1, 0x59, 0xe4, 0x9e, 0x98, 0x09,
	0xdf, 0x48, 0x8e, 0x4f, 0x7a, 0x80, 0x69, 0xd7, 0xd7, 0xec, 0xc9, 0x99, 0xf0, 0xdd, 0xc8, 0x09,
	0xeb, 0x2c, 0xd4, 0xe9, 0xa6, 0xaf, 0x39, 0xd1, 0x23, 0x7a, 0x02, 0xb3, 0xe4, 0x2f, 0x2e, 0x3d,
	0x43, 0x37, 0xee, 0xa5, 0x59, 0x1e, 0x6d, 0x72, 0x1a, 0x06, 0x3e, 0xdc, 0xbd, 0xa6, 0x3b, 0x5e,
	0x71, 0xdb, 0xa6, 0x5b, 0x26, 0x13, 0x84, 0xc2, 0x09, 0x11, 0xb8, 0x09, 0x1f, 0xd4, 0xf5, 0x0b,
	0x28, 0x82, 0x00, 0xec, 0xcb, 0x0a, 0x72, 0xc0, 0x7e, 0x2f, 0x7e, 0xd6, 0x65, 0xda, 0x73, 0x83,
	0x13, 0x72, 0x01, 0xde, 0x8a, 0x3d, 0x9f, 0x59, 0x04, 0xbf, 0x02, 0xe0, 0xba, 0x8b, 0x2c, 0x90,
	0x4a, 0x9d, 0x32, 0x2d, 0x96, 0xd5, 0xb7, 0x9a, 0xa3, 0x18, 0x70, 0x84, 0x72, 0xc0, 0x31, 0x1a,
	0x03, 0x5e, 0xe0, 0x94, 0xee, 0xc1, 0xd1, 0xbc, 0x2a, 0xf2, 0xbc, 0x64, 0x35, 0x47, 0x73, 0xac,
	0x22, 0xb4, 0xc6, 0x2a, 0xc6, 0x9b, 0xb1, 0x5a, 0xe0, 0xed, 0xb3, 0xf9, 0x27, 0xe5, 0x3a, 0xcb,
	0x2c, 0x7d, 0xf6, 0xf8, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xfe, 0x0e, 0x04, 0x83, 0x01, 0x00,
	0x00,
}
