// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//协议号
type GameMessage int32

const (
	GameMessage_Req_Login      GameMessage = 0
	GameMessage_Req_EnterTable GameMessage = 1
)

var GameMessage_name = map[int32]string{
	0: "Req_Login",
	1: "Req_EnterTable",
}

var GameMessage_value = map[string]int32{
	"Req_Login":      0,
	"Req_EnterTable": 1,
}

func (x GameMessage) String() string {
	return proto.EnumName(GameMessage_name, int32(x))
}

func (GameMessage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

//桌子类型
type TableType int32

const (
	TableType_SixPlayer  TableType = 0
	TableType_NinePlayer TableType = 1
)

var TableType_name = map[int32]string{
	0: "SixPlayer",
	1: "NinePlayer",
}

var TableType_value = map[string]int32{
	"SixPlayer":  0,
	"NinePlayer": 1,
}

func (x TableType) String() string {
	return proto.EnumName(TableType_name, int32(x))
}

func (TableType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

//桌子押注级别
type TableLevel int32

const (
	TableLevel_LevelLow_1 TableLevel = 0
	TableLevel_LevelLow_2 TableLevel = 1
	TableLevel_LevelLow_3 TableLevel = 2
	TableLevel_LevelLow_4 TableLevel = 3
)

var TableLevel_name = map[int32]string{
	0: "LevelLow_1",
	1: "LevelLow_2",
	2: "LevelLow_3",
	3: "LevelLow_4",
}

var TableLevel_value = map[string]int32{
	"LevelLow_1": 0,
	"LevelLow_2": 1,
	"LevelLow_3": 2,
	"LevelLow_4": 3,
}

func (x TableLevel) String() string {
	return proto.EnumName(TableLevel_name, int32(x))
}

func (TableLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

//登录游戏
type ReqLogin struct {
	Pid                  int32    `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

//请求入桌
type ReqEnterTable struct {
	Pid                  int32      `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Type                 TableType  `protobuf:"varint,2,opt,name=type,proto3,enum=pb.TableType" json:"type,omitempty"`
	Level                TableLevel `protobuf:"varint,3,opt,name=level,proto3,enum=pb.TableLevel" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReqEnterTable) Reset()         { *m = ReqEnterTable{} }
func (m *ReqEnterTable) String() string { return proto.CompactTextString(m) }
func (*ReqEnterTable) ProtoMessage()    {}
func (*ReqEnterTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *ReqEnterTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEnterTable.Unmarshal(m, b)
}
func (m *ReqEnterTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEnterTable.Marshal(b, m, deterministic)
}
func (m *ReqEnterTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEnterTable.Merge(m, src)
}
func (m *ReqEnterTable) XXX_Size() int {
	return xxx_messageInfo_ReqEnterTable.Size(m)
}
func (m *ReqEnterTable) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEnterTable.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEnterTable proto.InternalMessageInfo

func (m *ReqEnterTable) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ReqEnterTable) GetType() TableType {
	if m != nil {
		return m.Type
	}
	return TableType_SixPlayer
}

func (m *ReqEnterTable) GetLevel() TableLevel {
	if m != nil {
		return m.Level
	}
	return TableLevel_LevelLow_1
}

func init() {
	proto.RegisterEnum("pb.GameMessage", GameMessage_name, GameMessage_value)
	proto.RegisterEnum("pb.TableType", TableType_name, TableType_value)
	proto.RegisterEnum("pb.TableLevel", TableLevel_name, TableLevel_value)
	proto.RegisterType((*ReqLogin)(nil), "pb.ReqLogin")
	proto.RegisterType((*ReqEnterTable)(nil), "pb.ReqEnterTable")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x3b, 0x13, 0x23, 0xe6, 0x4a, 0xc2, 0x70, 0x57, 0x59, 0xb8, 0xa8, 0xc5, 0x45, 0xc9,
	0x22, 0x68, 0xeb, 0x13, 0x08, 0xe2, 0x26, 0x4a, 0x19, 0xbb, 0x2f, 0x19, 0xbc, 0x84, 0xc8, 0x34,
	0x33, 0xf9, 0x41, 0xcd, 0x2b, 0xf9, 0x94, 0x32, 0x53, 0x49, 0x29, 0xdd, 0xdd, 0x6f, 0xce, 0x07,
	0xe7, 0x30, 0x10, 0xed, 0xfb, 0x2a, 0xb7, 0x9d, 0x19, 0x0c, 0x72, 0xab, 0x16, 0x37, 0x70, 0x25,
	0xa9, 0x2d, 0x4c, 0x55, 0x37, 0x28, 0x20, 0xb0, 0xf5, 0x47, 0xca, 0xe6, 0x6c, 0x19, 0x4a, 0x77,
	0x2e, 0x3e, 0x21, 0x96, 0xd4, 0x3e, 0x37, 0x03, 0x75, 0xdb, 0x52, 0x69, 0x3a, 0x57, 0xf0, 0x16,
	0x2e, 0x86, 0xd1, 0x52, 0xca, 0xe7, 0x6c, 0x99, 0xac, 0xe2, 0xdc, 0xaa, 0xdc, 0xab, 0xdb, 0xd1,
	0x92, 0xf4, 0x11, 0xde, 0x41, 0xa8, 0xe9, 0x8b, 0x74, 0x1a, 0x78, 0x27, 0x99, 0x9c, 0xc2, 0xbd,
	0xca, 0x43, 0x98, 0xdd, 0xc3, 0xf5, 0x4b, 0xb9, 0xa7, 0x57, 0xea, 0xfb, 0xb2, 0x22, 0x8c, 0x21,
	0x92, 0xd4, 0xee, 0xfc, 0x32, 0x31, 0x43, 0x84, 0xc4, 0xe1, 0x71, 0x8a, 0x60, 0x59, 0x06, 0xd1,
	0x54, 0xe5, 0xfc, 0xf7, 0xfa, 0x67, 0xa3, 0xcb, 0x91, 0x3a, 0x31, 0xc3, 0x04, 0xe0, 0xad, 0x6e,
	0xe8, 0x9f, 0x59, 0x56, 0x00, 0x1c, 0x2b, 0x5d, 0xea, 0x8f, 0xc2, 0x7c, 0xef, 0x1e, 0x0e, 0xf6,
	0xc4, 0x2b, 0xc1, 0x4e, 0x78, 0x2d, 0xf8, 0x09, 0x3f, 0x8a, 0xe0, 0x29, 0xfc, 0xe5, 0x7c, 0xa3,
	0xd4, 0xa5, 0xff, 0xc7, 0xf5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xda, 0x4d, 0x5c, 0x54,
	0x01, 0x00, 0x00,
}
